### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by wt12318** [krishnanlab/txt2onto#5]
Hi, 
Thank you for offering this tool.
I download the docker and run it , but some error happened: 

```
docker build .
docker run -it 5e3054ed0944 /bin/bash
```
```
root@7ec114739cf4:/txt2onto# python src/txt2onto.py -h
Traceback (most recent call last):
  File "src/txt2onto.py", line 15, in <module>
    from utils import loadDictionary, makeStackedEmbedding, createEmbeddingFromText, loadAllModels
  File "/txt2onto/src/utils.py", line 24, in <module>
    from flair.data import Sentence
  File "/usr/local/lib/python3.7/site-packages/flair/__init__.py", line 4, in <module>
    from transformers import set_seed as hf_set_seed
  File "/usr/local/lib/python3.7/site-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.7/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/usr/local/lib/python3.7/site-packages/transformers/utils/versions.py", line 94, in require_version_core
    return require_version(requirement, hint)
  File "/usr/local/lib/python3.7/site-packages/transformers/utils/versions.py", line 85, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "/usr/local/lib/python3.7/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'
```
How to handle this problem?
Thanks

**Comment by aomdahl** [comment]
I am encountering the same error. There appears to be some versioning requirement conflict, or a possible issue in the version specification.

UPDATE:
There appears to be some kind of error in the `transformers` package dependencies table (given in: `/lib/python3.7/site-packages/transformers/dependency_versions_table.py`) for this version. I dropped  the "0.10.1," requirement for the `tokenizer` package and that seemed to get things running fine.
